#!/usr/bin/env bash
#
# Starts a local mosquitto with password authentication, for use behind an
# ngrok TCP tunnel.
#
# This exists separately from the repo's top-level mosquitto.conf because that
# one sets `allow_anonymous true`. That's fine for a broker only reachable on
# your LAN, and a liability the moment ngrok gives it a public address --
# anyone who learns the tunnel endpoint could subscribe to your data or publish
# forged batches into it.
#
# Usage:
#   MQTT_USER=esp32 MQTT_PASS='<password>' ./deploy/start-local-broker.sh
#
# Runtime state (config, password file, persistence) lands in .mosquitto/ at
# the repo root, which is git-ignored.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUNDIR="$REPO/.mosquitto"
CONF="$RUNDIR/mosquitto.conf"
PASSWD="$RUNDIR/passwd"

die() { echo "ERROR: $*" >&2; exit 1; }

[[ -n "${MQTT_USER:-}" ]] || die "MQTT_USER not set"
[[ -n "${MQTT_PASS:-}" ]] || die "MQTT_PASS not set"
command -v mosquitto >/dev/null || die "mosquitto not installed (brew install mosquitto)"

mkdir -p "$RUNDIR"

echo "==> Writing password file"
# mosquitto 2.1's -c refuses to overwrite an existing file, so clear it first.
# This broker only ever holds the single account below, so recreating it is
# what makes the script safely re-runnable.
rm -f "$PASSWD"
mosquitto_passwd -c -b "$PASSWD" "$MQTT_USER" "$MQTT_PASS"
chmod 0600 "$PASSWD"

echo "==> Writing config"
cat > "$CONF" <<EOF
# Generated by deploy/start-local-broker.sh -- do not edit by hand.
# Local broker with auth, intended to sit behind an ngrok TCP tunnel.

# Plain MQTT. ngrok forwards its public TCP endpoint to this port, so the
# ESP32 reaches it over cellular; local subscribers use 127.0.0.1:1883
# directly rather than paying a round trip through the tunnel.
listener 1883 0.0.0.0
protocol mqtt

# WebSocket, for web/dashboard.html. Reachable on the LAN as-is; exposing it
# publicly would need a second ngrok tunnel, which the free plan does not
# allow concurrently with the TCP one.
listener 9001 0.0.0.0
protocol websockets

allow_anonymous false
password_file $PASSWD

persistence true
persistence_location $RUNDIR/

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
EOF

# Free the port if something is already on it -- typically a stale broker from
# an earlier run, which would otherwise silently keep serving the old config.
if lsof -nP -iTCP:1883 -sTCP:LISTEN >/dev/null 2>&1; then
    echo "==> Stopping existing broker on port 1883"
    pkill -x mosquitto || true
    sleep 1
fi

echo "==> Starting mosquitto"
mosquitto -c "$CONF" -d
sleep 1

pgrep -x mosquitto >/dev/null || die "mosquitto failed to start"

echo "==> Verifying"
# -W rather than timeout(1): macOS has no timeout, only gtimeout via coreutils.
mosquitto_sub -W 10 -h 127.0.0.1 -p 1883 -u "$MQTT_USER" -P "$MQTT_PASS" \
    -t 'sdm27/selftest' -C 1 > "$RUNDIR/selftest.out" &
SUB_PID=$!
sleep 1
mosquitto_pub -h 127.0.0.1 -p 1883 -u "$MQTT_USER" -P "$MQTT_PASS" \
    -t 'sdm27/selftest' -m ok
wait $SUB_PID 2>/dev/null || true
grep -q ok "$RUNDIR/selftest.out" \
    && echo "    authenticated publish/subscribe works" \
    || die "self-test round trip failed"
rm -f "$RUNDIR/selftest.out"

# The check that matters before opening a tunnel to this.
if mosquitto_sub -W 5 -h 127.0.0.1 -p 1883 -t 'sdm27/#' -C 1 >/dev/null 2>&1; then
    die "anonymous subscribe SUCCEEDED -- do not expose this broker"
else
    echo "    anonymous access correctly refused"
fi

echo
echo "Broker up on 1883 (mqtt) and 9001 (websockets), auth required."
echo "Next: ngrok tcp 1883"
